export const state = {
  overview: null,
  view: null,
  currentChunkId: null,
  selectedUnit: null,
  selectedReviewTarget: null,
  referenceTab: "source",
  editorMode: "edit",
  evidenceInspectorOpen: false,
  evidenceInspectorMinimized: false,
  issueLedgerOpen: true,
  splitPercent: 48,
  focusEditor: false,
  issueFilter: "open",
  reviewMode: "review",
  layers: {
    deterministic: true,
    witness_disagreement: true,
    prosecutor: true,
    adjudicator: true,
    adjudicator_edit: true,
    unresolved: true,
    human_review: true,
    verification: true,
    source_mapping: true,
    editorial_note: true,
  },
  reviewIndex: null,
  resolutions: new Map(),
  annotations: [],
  dirty: false,
  saving: false,
};

export const LAYER_LABELS = {
  deterministic: "Deterministic",
  witness_disagreement: "Disagreements",
  prosecutor: "Prosecutor",
  adjudicator: "Adjudicator findings",
  adjudicator_edit: "Adjudicator edits",
  unresolved: "Unresolved",
  human_review: "Human review",
  verification: "Verification",
  source_mapping: "Source mappings",
  editorial_note: "Editorial notes",
};
